# Generated by Django 3.1.6 on 2021-02-11 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TypeOfMeasurment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measurment', models.CharField(max_length=64, unique=True, verbose_name='вид измерения')),
            ],
        ),
        migrations.CreateModel(
            name='MeasuringInstrument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='наименование си')),
                ('state_register_number', models.CharField(max_length=16, verbose_name='ГРСИ си')),
                ('year', models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='год выпуска си')),
                ('invertarian_number', models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='инвертарный номер си')),
                ('factory_number', models.CharField(max_length=16, verbose_name='заводской номер си')),
                ('owner', models.CharField(max_length=128, verbose_name='владелец си')),
                ('status', models.CharField(choices=[('in repair', 'В ремонте'), ('in work', 'В работе'), ('in verification', 'На поверке'), ('in calibration', 'На калибровке'), ('in storage', 'На хранении')], default='in_storage', max_length=16)),
                ('typeofmeasurment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metrologyapp.typeofmeasurment')),
            ],
        ),
    ]
