# Generated by Django 3.1.6 on 2021-02-11 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrologyapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measuringinstrument',
            name='invertarian_number',
            field=models.CharField(default=0, max_length=6, verbose_name='инвертарный номер си'),
        ),
        migrations.AlterField(
            model_name='measuringinstrument',
            name='year',
            field=models.CharField(default=0, max_length=4, verbose_name='год выпуска си'),
        ),
    ]
